local_costmap:
  map_type: costmap
  global_frame: map
  robot_base_frame: base_footprint

  update_frequency: 5.0
  transform_tolerance: 0.5   # Tolerable delay 
  publish_frequency: 5.0 #rate in Hz that costmap will publish visualization info
  
  static_map: false 
  rolling_window: true #costmap will remain centered around robot
  width: 1.0 #width of costmap
  height: 1.0 #height of costmap
  resolution: 0.05 #meters/cell, usually resolution is same as resolution of static map  